config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'form_capacities/edit'
  get 'form_capacities/update'
  resources :inventory_histories
  resources :inventories do
    collection do
      get 'generate_report'
    end
  end
  resources :staff_activities
  resources :club_advisors
  resources :clubs_advisors
  resources :students do
    member do
      patch :update_score
    end
  end
  resources :staffs do
    collection do
      get 'studentsList', to: 'staffs#studentsList'
      get 'staffList', to: 'staffs#staffList' # Adding staffList route
    end
  
    member do
      get 'stuInfo/:id', to: 'staffs#stuInfo', as: 'stuInfo' 
    end
  end
  resources :club_members
  resources :attendances
  resources :extra_activities

  resources :clubs do
    resource :form_capacity, only: [:edit, :update]
    get 'edit_form_capacity', to: 'clubs#edit_form_capacity', on: :member
    resources :activities, only: [:new, :create]
    collection do
      get 'displayactivity'
      #This means, if the clubs/xx equals to one of the gets below, lead to the to: page
      get 'finance', to: 'clubs#finance'
      get 'editBudget', to: 'clubs#editBudget'
      get 'generate_report', to: 'clubs#generate_report', format: :csv
    end
  end

  resources :activities do
    collection do
      get 'editBudget'
      get 'displayactivity'
    end
  end

  

  
  get 'dashboard/generate_report', to: 'dashboard#generate_report', format: :csv, as: 'generate_report_dashboard'
  get '/clubs/show_students/:staff_id/:club_id', to: 'clubs#show_students', as: :show_students
  get 'dashboard/myTable', to: 'dashboards#my_table'
  get 'clubs/finance'
  root 'sessions#new'
  get 'dashboard', to: 'dashboard#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'activities/createActivity', to: 'activities#createActivity', as: 'createActivity'
  post '/upload', to: 'activities#upload'
  get 'activities/:id/media' => 'activities#media', as: :activity_media
  get 'attendances/:id/media' => 'attendances#media', as: :attendance_media

  get 'extra_activities/:id/evidence' => 'extra_activities#evidence', as: :extra_activity_evidence



end

app/models/staff.rb
class Staff < ApplicationRecord
    has_many :club_advisors
    has_many :clubs, through: :club_advisors
    has_many :staff_activities
    has_many :activities, through: :staff_activities
    has_secure_password

    #Add username (first_name+last_name+id)
    def full_name
        "#{first_name} #{last_name}"
    end


end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
    @activities = Activity.all
  end

  # GET /staffs/1 or /staffs/1.json


  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  def stuInfo
    @student = Student.find(params[:id])
    @attended_activities = Attendance.where(student_id: @student.id).map(&:activity)
    @external_activities = ExtraActivity.where(student_id: @student.id)
  end
  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to staff_url(@staff), notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staff_url(@staff), notice: "Staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end
  def studentsList
    @clubs = Club.all
    @activities = Activity.all
    @students = Student.all
  end
  def staffList
    @clubs = Club.all
    @staffs = Staff.all
  end
  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy!

    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "Staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:first_name, :last_name, :gender, :email, :phone)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/_staff.html.erb
<h1>Hello Dear <%= staff.first_name %></h1>
<h3 class="card-title">Clubs assigned: </h3>
<br>
<table class="table table-striped table-hover table-bordered border-dark">
  <thead class="table-success">
    <tr>
      <th>Club Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% staff.clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td>
          <%= button_to "Show Students", show_students_path(staff_id: staff.id, club_id: club.id), method: :get, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Show this staff", @staff %> |
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mt-4">
  <%# this is for the first part (clubs assigned) %>
  <%= render @staffs.first %>
  <%= render 'activities/index' %>
</div>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @staff %>
<!--<div>
  <%= link_to "Edit this staff", edit_staff_path(@staff) %> |
  <%= link_to "Back to staffs", staffs_path %>

  <%= button_to "Destroy this staff", @staff, method: :delete %>
</div>
-->

app/views/staffs/staffList.html.erb
<h1>Staff</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Staff ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Assigned Clubs</th>
      <!-- New column header -->
    </tr>
  </thead>
  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td data-label="Staff ID"><%= staff.id %></td>
        <td data-label="First Name"><%= staff.first_name %></td>
        <td data-label="Last Name"><%= staff.last_name %></td>
        <td data-label="Gender"><%= staff.gender %></td>
        <td data-label="Email"><%= staff.email %></td>
        <td data-label="Phone"><%= staff.phone %></td>
        <td data-label="Assigned Clubs">
          <% staff.clubs.each do |club| %>
            <%= club.name %><br>
          <% end %>
        </td>
      </tr>
        <% end %>
  </tbody>
</table>
<%= link_to 'Back to Dashboard', dashboard_path, class: 'btn btn-primary mb-3 col-12' %>

app/views/staffs/stuInfo.html.erb
<% if current_user.is_a?(Admin) %>
  <h1>Student Information</h1>
  <%= form_for @student, url: { controller: 'students', action: 'update_score', id: @student.id }, method: :patch do |f| %>
    <table class="table table-striped">
      <tr>
        <th>Student Id</th>
        <td><%= @student.id %></td>
      </tr>
      <tr>
        <th>Fullname</th>
        <td><%= "#{@student.first_name} #{@student.last_name}" %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= @student.parent_email %></td>
      </tr>
      <tr>
        <th>Clubs</th>
        <td>
          <% @student.clubs.each do |club| %>
            <%= "#{club.categories} - #{club.name} " %><br>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>CCTS Score</th>
        <td>
          <%= f.text_field :score, pattern: "\\d*", title: "Only numbers are allowed." %>
          <%= f.submit 'Save Score', class: 'btn btn-primary' %>
        </td>
      </tr>
    </table>
  <% end %>
<% elsif current_user.is_a?(Staff) %>
  <h1>Student Information</h1>
    <%= form_for @student, url: { controller: 'students', action: 'update_score', id: @student.id }, method: :patch do |f| %>
      <table class="table table-striped">
        <tr>
          <th>Student Id</th>
          <td><%= @student.id %></td>
        </tr>
        <tr>
          <th>Fullname</th>
          <td><%= "#{@student.first_name} #{@student.last_name}" %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @student.parent_email %></td>
        </tr>
        <tr>
          <th>Clubs</th>
          <td>
            <% @student.clubs.each do |club| %>
              <%= "#{club.categories} - #{club.name} " %><br>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>CCTS Score</th>
          <td>
            <%= @student.score %>
          </td>
        </tr>
      </table>
    <% end %>
<% end %>
<br>
<br>
<h1>Activity List</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Activity Title</th>
      <th>Description</th>
      <th>Clubs</th>
    </tr>
  </thead>
  <tbody>
    <% @attended_activities.each do |activity| %>
      <tr>
        <td data-label="Activity Title"><%= activity.activity_title %></td>
        <td data-label="Description"><%= activity.description %></td>
        <td data-label="Clubs"><%= activity.club.name %><br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--<%= link_to 'Back to Student List', studentsList_staffs_path, class: 'btn btn-primary' %>-->
<br>
<br>
<h1>External Activities</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Activity Name</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Evidence</th>
    </tr>
  </thead>
  <tbody>
    <% @external_activities.each do |extra_activity| %>
      <tr>
        <td data-label="Activity Name" ><%= extra_activity.name %></td>
        <td data-label="Description" ><%= extra_activity.description %></td>
        <td data-label="Start Date" ><%= extra_activity.start_date %></td>
        <td data-label="End Date" ><%= extra_activity.end_date %></td>
        <td data-label="Evidence">
          <% if extra_activity.evidence %>
            <%= extra_activity.evidence['filename'] %>
            <%= link_to 'Download', extra_activity_evidence_path(extra_activity.id), download: extra_activity.evidence['filename'] %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back To Students List', 'javascript:history.go(-1);', class: 'btn btn-primary mb-3 col-12' %>

app/views/staffs/studentsList.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Students List</h1>
  <%= form_tag students_path, method: :get, class: "form-inline" do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "🔍 Search by name" %>
    </div>
    <%= submit_tag "Search", class: "btn btn-success" %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student Id</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>CCTS Score</th>
      <th>Student Information</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td data-label="Student Id"><%= student.id %></td>
        <td data-label="First Name"><%= student.first_name %></td>
        <td data-label="Last Name"><%= student.last_name %></td>
        <td data-label="Email"><%= student.parent_email %></td>
        <td data-label="CCTS Score"><%= student.score %></td>
        <td>
          <%= link_to 'View Information', stuInfo_staff_path(id: student.id), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back to Dashboard', dashboard_path, class: 'btn btn-primary mb-3 col-12' %>