config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'form_capacities/edit'
  get 'form_capacities/update'
  resources :inventory_histories
  resources :inventories do
    collection do
      get 'generate_report'
    end
  end
  resources :staff_activities
  resources :club_advisors
  resources :clubs_advisors
  resources :students do
    member do
      patch :update_score
    end
  end
  resources :staffs do
    collection do
      get 'studentsList', to: 'staffs#studentsList'
      get 'staffList', to: 'staffs#staffList' # Adding staffList route
    end
  
    member do
      get 'stuInfo/:id', to: 'staffs#stuInfo', as: 'stuInfo' 
    end
  end
  resources :club_members
  resources :attendances
  resources :extra_activities

  resources :clubs do
    resource :form_capacity, only: [:edit, :update]
    get 'edit_form_capacity', to: 'clubs#edit_form_capacity', on: :member
    resources :activities, only: [:new, :create]
    collection do
      get 'displayactivity'
      #This means, if the clubs/xx equals to one of the gets below, lead to the to: page
      get 'finance', to: 'clubs#finance'
      get 'editBudget', to: 'clubs#editBudget'
      get 'generate_report', to: 'clubs#generate_report', format: :csv
    end
  end

  resources :activities do
    collection do
      get 'editBudget'
      get 'displayactivity'
    end
  end

  

  
  get 'dashboard/generate_report', to: 'dashboard#generate_report', format: :csv, as: 'generate_report_dashboard'
  get '/clubs/show_students/:staff_id/:club_id', to: 'clubs#show_students', as: :show_students
  get 'dashboard/myTable', to: 'dashboards#my_table'
  get 'clubs/finance'
  root 'sessions#new'
  get 'dashboard', to: 'dashboard#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'activities/createActivity', to: 'activities#createActivity', as: 'createActivity'
  post '/upload', to: 'activities#upload'
  get 'activities/:id/media' => 'activities#media', as: :activity_media
  get 'attendances/:id/media' => 'attendances#media', as: :attendance_media

  get 'extra_activities/:id/evidence' => 'extra_activities#evidence', as: :extra_activity_evidence



end

app/models/activity.rb
# app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :club
  has_many :attendance
  has_many :attendances
  has_many :club_advisors
  has_many :staffs, through: :club_advisors
  has_many :staff_activities
  has_many :staff, through: :staff_activities

  after_save :deduct_budget_from_club, if: -> { saved_change_to_status? && status == 'Approved' }

  attribute :status, :string, default: 'Pending'

  private


def deduct_budget_from_club
  return unless status_was == 'Pending' && status == 'Approved' && club_id.present?

  club = Club.find_by(id: club_id)
  
  if club.present? && club.budget >= requested_budget
    club.update(budget: club.budget - requested_budget)
  end
end

def self.approved
  where(status: "approved")
end

def self.pending
  where(status: "pending")
end

#testing
  scope :upcoming_activities, -> {
    where('start_date > ?', Time.current)
      .where('end_date > ?', Time.current)
      .order('start_date ASC')
      .limit(4)
  }
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password

    def full_name
        "#{first_name} #{last_name}"
    end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # validates_uniqueness_of :student_id, scope: :activity_id

 

  belongs_to :student
  belongs_to :activity
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :club_advisors
    has_many :staffs, through: :club_advisors
    has_many :activities
    has_many :club_members
    has_many :students, through: :club_members
    has_one  :form_capacity
    def form_capacity_for_form(form_number)
        form_capacity.find_by(form: form_number)
    end
    #To map the previous categories named column to renamed category column
    def categories
        category
    end
    
    #Will treat all categories as category when saving/updating values, so no need to change 1 by 1 inside the controllers and views
    def categories=(value)
        self.category = value
    end
end

app/models/club_advisor.rb
class ClubAdvisor < ApplicationRecord
  belongs_to :club
  belongs_to :staff
end

app/models/club_member.rb
class ClubMember < ApplicationRecord
  belongs_to :club
  belongs_to :student
end

app/models/extra_activity.rb
class ExtraActivity < ApplicationRecord
  belongs_to :student
end

app/models/form_capacity.rb
# app/models/form_capacity.rb
class FormCapacity < ApplicationRecord
    belongs_to :club
  
    validate :total_capacity_within_limit
  
    private
  
    def total_capacity_within_limit
      total_capacity = f1.to_i + f2.to_i + f3.to_i + f4.to_i + f5.to_i
      if total_capacity > club.capacity
        errors.add(:base, "Total form capacity exceeds maximum cl")
      end
    end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :inventory_histories, dependent: :destroy
end

app/models/inventory_history.rb
class InventoryHistory < ApplicationRecord
  belongs_to :inventory, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
    has_many :club_advisors
    has_many :clubs, through: :club_advisors
    has_many :staff_activities
    has_many :activities, through: :staff_activities
    has_secure_password

    #Add username (first_name+last_name+id)
    def full_name
        "#{first_name} #{last_name}"
    end


end

app/models/staff_activity.rb
class StaffActivity < ApplicationRecord
  belongs_to :staff
  belongs_to :activity
  
end

app/models/student.rb
# app/models/student.rb
class Student < ApplicationRecord
    has_many :attendances
    has_many :club_members
    has_many :clubs, through: :club_members
    has_many :extra_activities
    has_secure_password
  
    def full_name
        "#{first_name} #{last_name}"
    end
    
    def self.search(search)
        if search
          where("first_name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%")
        else
          all
        end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'csv'
  def index
  end
  
    def generate_report
      @students = Student.all
      @staffs = Staff.all
    
      respond_to do |format|
        format.csv do
          report_name = "StudentsAndStaffReport_#{Date.today.strftime('%Y-%m-%d')}.csv"
          headers['Content-Disposition'] = "attachment; filename=#{report_name}"
          headers['Content-Type'] ||= 'text/csv'
    
          csv_data = CSV.generate do |csv|
            # Students data
            student_attributes = ["Student ID", "First Name", "Last Name", "Gender", "Parent Phone", "Parent Email", "Score", "Stud ID", "Form"]
            csv << student_attributes
            @students.each do |student|
              csv << [student.id, student.first_name, student.last_name, student.gender, student.parent_phone, student.parent_email, student.score, student.stud_id, student.form]
            end
            csv << [""]
    
            # Staffs data
            staff_attributes = ["Staff ID", "First Name", "Last Name", "Gender", "Email", "Phone"]
            csv << staff_attributes
            @staffs.each do |staff|
              csv << [staff.id, staff.first_name, staff.last_name, staff.gender, staff.email, staff.phone]
            end
          end
    
          send_data csv_data, filename: report_name
        end
      end
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def is_mobile?
        browser.device.mobile?
    end
      
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dashboard/_graph1.html.erb
<h3>Clubs Budget (RM)</h3>
<%= column_chart Club.group(:Name ).sum(:budget)%>

app/views/dashboard/_graph2.html.erb
<h3>Activities Budget (RM)</h3>
<%= column_chart Activity.joins(:club).where(status: "Approved").group("clubs.name", "activities.activity_title").sum(:requested_budget), discrete: true, stacked: true, colors: ["#2196F3", "#F44336", "#FFEB3B", "#8BC34A", "#9E9E9E"], legend: "bottom" %>

app/views/dashboard/_graph3.html.erb
<h3>Pending Budgets (RM)</h3>
<%= column_chart Activity.joins(:club).where(status: "Pending").group("clubs.name", "activities.activity_title").sum(:requested_budget), discrete: true, stacked: true, colors: ["#2196F3", "#F44336", "#FFEB3B", "#8BC34A", "#9E9E9E"], legend: "bottom" %>

app/views/dashboard/_myTable.html.erb
<% if current_user.is_a?(Staff) %>
<div class="myTable">
<h3> Assigned Clubs </h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Club Name</th>
        <th>Budget (RM)</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.club_advisors.each do |club_advisor| %>
        <tr>
          <td data-label="Club Name:"><%= club_advisor.club.name %></td>
          <td data-label="Budget (RM):"><%= number_with_precision(club_advisor.club.budget, precision: 2) %></td>
          <td>
            <%= button_to "Show Assigned Students", show_students_path(staff_id: club_advisor.staff.id, club_id: club_advisor.club.id), method: :get, class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><br>
  <h3> Activities </h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Requested Budget (RM)</th>
        <th>Club Name</th>
        <th>Status</th>
 
        <th colspan="2"style="text-align: center;" >Actions</th>
      </tr>
    </thead>
    
    <tbody>
      <% ClubAdvisor.where(staff_id: current_user.id).each do |club_advisor| %>
  <% club = club_advisor.club %>
  <% club.activities.each do |activity| %>
    <tr>
      <td data-label = "Title:"><%= activity.activity_title %></td>
      <td data-label = "Description:"><%= activity.description %></td>
      <td data-label = "Requested Budget (RM):"><%= number_with_precision(activity.requested_budget, precision: 2) %></td>
      <td data-label = "Club Name:"><%= club.name %></td>
      <td data-label = "Status:"><%= activity.status %></td>

      <td ><%= link_to 'Manage', activity, class: 'btn btn-primary btn-sm' %></td>
      <td ><%= link_to 'Attendance', new_attendance_path(activity_id: activity.id), class: 'btn btn-info btn-sm' %></td>
    </tr>
  <% end %>
<% end %>
    </tbody>
  </table>
  <%= link_to 'New Activity', new_activity_path, class: 'btn btn-success mb-3 col-12' %>
</div>
<% elsif current_user.is_a?(Student) %>
  <% if current_user.club_members.any? %>
    <h1>Enrolled Clubs</h1>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Category</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.club_members.each do |club_member| %>
        <tr>
          <td data-label = "Category" ><%= club_member.club.categories %></td>
          <td data-label = "Name"><%= club_member.club.name %></td>
          <td data-label = "Description"><%= club_member.club.description %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% else %>
    <!--<%= current_user.id%>-->
    <%= link_to "Enroll Club", new_club_member_path(student_id: current_user.id), class: "btn btn-primary mb-3 col-12" %>
    <br>
  <% end %>
    <br><br>
  <h1>Activity Participation</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Club</th>
        <th>Title</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th class='text-center'>Media</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.attendances.each do |attendance| %>
        <tr>
          <td data-label = "Club" ><%= attendance.activity.club.name %></td>
          <td data-label = "Title" ><%= attendance.activity.activity_title %></td>
          <td data-label = "Description" ><%= attendance.activity.description %></td>
          <td data-label = "Start Date" ><%= attendance.activity.start_date %></td>
          <td data-label = "End Date"><%= attendance.activity.end_date %></td>
          <td data-label = "Media">
            <% if attendance && attendance.activity && attendance.activity.media %>
              <%= link_to 'Download Media', attendance_media_path(attendance.id), download: attendance.activity.media['filename'] %>
            <% else %>
              No Media Available
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><br>
  <h1>External Activity Participation</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th class='text-center'>Action</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.extra_activities.each do |extra_activity| %>
        <tr>
          <td data-label = "Name"><%= extra_activity.name %></td>
          <td data-label = "Description"><%= extra_activity.description %></td>
          <td data-label = "Start Date"><%= extra_activity.start_date %></td>
          <td data-label = "End Date"><%= extra_activity.end_date %></td>
          <td class='text-center'><%= link_to "Show", extra_activity, class: "btn btn-primary"%>
          </td>
        </tr>
      <% end %>
    </tbody>

    
  </table>
  <%= link_to "Submit External Activity", new_extra_activity_path, class: "btn btn-success mb-3 col-12" %>
  <br>
  <br>
<% end %>

app/views/dashboard/index.html.erb
<div class="row">
    <div class="col-md-12">
      <%= render 'dashboard/graph1' if current_user.is_a?(Admin) %>
    </div>
</div>
<br><br><br><br>
<div class="row">
  <div class="col-md-6">
    <%= render 'dashboard/graph2' if current_user.is_a?(Admin) %>
  </div>
  <div class="col-md-6">
    <%= render 'dashboard/graph3' if current_user.is_a?(Admin) %>
  </div>
</div>
<%= render 'dashboard/myTable' if current_user.is_a?(Staff) || current_user.is_a?(Student) %>
<% if current_user.is_a?(Admin) %>
  <div class="text-center mt-5 mb-5">
    <%= link_to 'Generate Staff and Student Report', generate_report_dashboard_path(format: :csv), class: 'btn btn-success btn-lg col-12' %>
  </div>
<% end %>