config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'form_capacities/edit'
  get 'form_capacities/update'
  resources :inventory_histories
  resources :inventories do
    collection do
      get 'generate_report'
    end
  end
  resources :staff_activities
  resources :club_advisors
  resources :clubs_advisors
  resources :students do
    member do
      patch :update_score
    end
  end
  resources :staffs do
    collection do
      get 'studentsList', to: 'staffs#studentsList'
      get 'staffList', to: 'staffs#staffList' # Adding staffList route
    end
  
    member do
      get 'stuInfo/:id', to: 'staffs#stuInfo', as: 'stuInfo' 
    end
  end
  resources :club_members
  resources :attendances
  resources :extra_activities

  resources :clubs do
    resource :form_capacity, only: [:edit, :update]
    get 'edit_form_capacity', to: 'clubs#edit_form_capacity', on: :member
    resources :activities, only: [:new, :create]
    collection do
      get 'displayactivity'
      #This means, if the clubs/xx equals to one of the gets below, lead to the to: page
      get 'finance', to: 'clubs#finance'
      get 'editBudget', to: 'clubs#editBudget'
      get 'generate_report', to: 'clubs#generate_report', format: :csv
    end
  end

  resources :activities do
    collection do
      get 'editBudget'
      get 'displayactivity'
    end
  end

  

  
  get 'dashboard/generate_report', to: 'dashboard#generate_report', format: :csv, as: 'generate_report_dashboard'
  get '/clubs/show_students/:staff_id/:club_id', to: 'clubs#show_students', as: :show_students
  get 'dashboard/myTable', to: 'dashboards#my_table'
  get 'clubs/finance'
  root 'sessions#new'
  get 'dashboard', to: 'dashboard#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'activities/createActivity', to: 'activities#createActivity', as: 'createActivity'
  post '/upload', to: 'activities#upload'
  get 'activities/:id/media' => 'activities#media', as: :activity_media
  get 'attendances/:id/media' => 'attendances#media', as: :attendance_media

  get 'extra_activities/:id/evidence' => 'extra_activities#evidence', as: :extra_activity_evidence



end

app/models/activity.rb
# app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :club
  has_many :attendance
  has_many :attendances
  has_many :club_advisors
  has_many :staffs, through: :club_advisors
  has_many :staff_activities
  has_many :staff, through: :staff_activities

  after_save :deduct_budget_from_club, if: -> { saved_change_to_status? && status == 'Approved' }

  attribute :status, :string, default: 'Pending'

  private


def deduct_budget_from_club
  return unless status_was == 'Pending' && status == 'Approved' && club_id.present?

  club = Club.find_by(id: club_id)
  
  if club.present? && club.budget >= requested_budget
    club.update(budget: club.budget - requested_budget)
  end
end

def self.approved
  where(status: "approved")
end

def self.pending
  where(status: "pending")
end

#testing
  scope :upcoming_activities, -> {
    where('start_date > ?', Time.current)
      .where('end_date > ?', Time.current)
      .order('start_date ASC')
      .limit(4)
  }
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password

    def full_name
        "#{first_name} #{last_name}"
    end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # validates_uniqueness_of :student_id, scope: :activity_id

 

  belongs_to :student
  belongs_to :activity
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :club_advisors
    has_many :staffs, through: :club_advisors
    has_many :activities
    has_many :club_members
    has_many :students, through: :club_members
    has_one  :form_capacity
    def form_capacity_for_form(form_number)
        form_capacity.find_by(form: form_number)
    end
    #To map the previous categories named column to renamed category column
    def categories
        category
    end
    
    #Will treat all categories as category when saving/updating values, so no need to change 1 by 1 inside the controllers and views
    def categories=(value)
        self.category = value
    end
end

app/models/club_advisor.rb
class ClubAdvisor < ApplicationRecord
  belongs_to :club
  belongs_to :staff
end

app/models/club_member.rb
class ClubMember < ApplicationRecord
  belongs_to :club
  belongs_to :student
end

app/models/extra_activity.rb
class ExtraActivity < ApplicationRecord
  belongs_to :student
end

app/models/form_capacity.rb
# app/models/form_capacity.rb
class FormCapacity < ApplicationRecord
    belongs_to :club
  
    validate :total_capacity_within_limit
  
    private
  
    def total_capacity_within_limit
      total_capacity = f1.to_i + f2.to_i + f3.to_i + f4.to_i + f5.to_i
      if total_capacity > club.capacity
        errors.add(:base, "Total form capacity exceeds maximum cl")
      end
    end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :inventory_histories, dependent: :destroy
end

app/models/inventory_history.rb
class InventoryHistory < ApplicationRecord
  belongs_to :inventory, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
    has_many :club_advisors
    has_many :clubs, through: :club_advisors
    has_many :staff_activities
    has_many :activities, through: :staff_activities
    has_secure_password

    #Add username (first_name+last_name+id)
    def full_name
        "#{first_name} #{last_name}"
    end


end

app/models/staff_activity.rb
class StaffActivity < ApplicationRecord
  belongs_to :staff
  belongs_to :activity
  
end

app/models/student.rb
# app/models/student.rb
class Student < ApplicationRecord
    has_many :attendances
    has_many :club_members
    has_many :clubs, through: :club_members
    has_many :extra_activities
    has_secure_password
  
    def full_name
        "#{first_name} #{last_name}"
    end
    
    def self.search(search)
        if search
          where("first_name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%")
        else
          all
        end
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/shared/_calendar.html.erb
<div class="calendar-container">
  <%= month_calendar do |date| %>
    <div class="day <%= 'today' if date == Date.current %>">
      <%= date.day %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class='head_container'>
  <div class='School_logo'>
    <%= link_to image_tag("semi-1.png", alt: "semi abim logo", style: "width: 100px; height: 100px;"), dashboard_path %>
    <div class='logo-text'>
      <div class="logo-text1">Good Day 💫</div>
      <div class="logo-text2">
        <!-- Add the welcome message and the user role here -->
        <% if current_user.is_a?(Student) %> 
          <p>Welcome, <%= current_user.full_name %>! </p> 
        <% elsif current_user.is_a?(Staff) %> 
          <p>Welcome, <%= current_user.full_name %>! </p> 
        <% elsif current_user.is_a?(Admin) %> 
          <p>Welcome, <%= current_user.full_name %>! </p> 
        <% end %>
      </div>
    </div>
  </div>
  <div class="header-content">
    <div class="dashboard-text">
        <!-- Show User dashboard and the user role here -->
        <% if current_user.is_a?(Student) %> 
          <p>....Student/<span style="color: orange;">Dashboard</span></p> 
        <% elsif current_user.is_a?(Staff) %> 
          <p>....Staff/<span style="color: orange;">Dashboard</span></p> 
        <% elsif current_user.is_a?(Admin) %> 
          <p>....Admin/<span style="color: orange;">Dashboard</span></p> 
        <% end %>
      </div>
    <div class="notification">
      <%= image_tag "notification.png", alt: "notification", class: "notification-icon"%>
    </div>
  </div>
</nav>

app/views/shared/_miniDash.html.erb
<div class="dashboard-container">
  <div class="dashboard "> <!-- Added the  class -->
    <div class="circle-icon">
      <!-- Use image_path to get the correct image URL -->
      <img src="<%= image_path('student.png') %>" alt="Icon">
    </div>
    <div class="dashboard-text">STUDENTS</div>
    <div class="dashboard-number"><%= Student.count %></div>
  </div>
  <div class="dashboard "> <!-- Added the  class -->
    <div class="circle-icon">
      <!-- Use image_path to get the correct image URL -->
      <img src="<%= image_path('staff.png') %>" alt="Icon">
    </div>
    <div class="dashboard-text">STAFF</div>
    <div class="dashboard-number"><%= Staff.count %></div>
  </div>
  <div class="dashboard "> <!-- Added the  class -->
    <div class="circle-icon">
      <!-- Use image_path to get the correct image URL -->
      <img src="<%= image_path('activity.png') %>" alt="Icon">
    </div>
    <div class="dashboard-text">ACTIVITIES</div>
    <div class="dashboard-number"><%= Activity.count %></div>
  </div>
</div>

app/views/shared/_sideBar.html.erb
<div calss = "main-menu">
  <div class="sidebar">
  <div>
    <!-- Icon for Dashboard -->
    <div class="icon" title="Dashboard">
      <%= link_to dashboard_path, class: "custom-link" do %>
        <i class="fa fa-bar-chart"></i>
      <% end %>
    </div>
    <!-- Icon for Staff -->
    <div class="icon" title="Staff">
      <%= link_to staffList_staffs_path, class: "custom-link" do %>
        <i class="fa-solid fa-person-chalkboard"></i>
      <% end %>
    </div>
    <!-- Icon for Students -->
    <div class="icon" title="Students">
      <%= link_to studentsList_staffs_path, class: "custom-link" do %>
        <i class="fa-solid fa-user-graduate"></i>
      <% end %>
    </div>
    <!-- Icon for Clubs -->
    <div class="icon" title="Clubs">
      <%= link_to clubs_path, class: "custom-link" do %>
        <i class="fa-solid fa-flag"></i>
      <% end %>
    </div>
    <!-- Icon for Finance -->
    <div class="icon" title="Finance">
      <%= link_to clubs_finance_path, class: "custom-link" do %>
        <i class="fa fa-usd"></i>
      <% end %>
    </div>
    <!-- Icon for Inventory-->
    <div class="icon" title="Inventory">
      <%= link_to inventories_path, class: "custom-link" do %>
        <i class="fa-solid fa-warehouse"></i>
      <% end %>
    </div>
  </div>
  <div class="icon" title="Help">
    <i class="fa fa-question-circle"></i>
  </div>
</div>
</div>

app/views/shared/_upcomingEvents.html.erb
<!-- _upcoming_event.html.erb -->
    <%= stylesheet_link_tag "upcomingEvents" %>

<div class="card upcoming-events-card">
  <p style="font-weight: normal; font-size: 25px">Upcoming Activities</p>
  <div>
<table class="default-table" style="margin-bottom: 10%;">
        <% if @upcoming_activities.present? %>
        <% @upcoming_activities.each do |activity| %>
          <tr>
            <td></td> <!-- Your empty column -->
            <td>
              <%= activity.activity_title %><br>
              <%= activity.description %><br>
              <div class="float"><%= activity.start_date %> - <%= activity.end_date%></div>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td></td><td colspan="2">No upcoming activities</td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/shared/_userCard.html.erb
<div class="user-card">
  <img src="<%= image_path('account_icon.jpg') %>" alt="Profile Picture" class="profile-pic">
  <div class="user-info">
    <div class="username">
      <% if current_user.is_a?(Student) %> 
        <p>Welcome, <%= current_user.full_name %>! </p> 
      <% elsif current_user.is_a?(Staff) %> 
        <p>Welcome, <%= current_user.full_name %>! </p> 
      <% elsif current_user.is_a?(Admin) %> 
        <p>Welcome, <%= current_user.full_name %>!</p> 
      <% end %>
    </div>
    <%= button_to "Logout", logout_path, method: :delete, class: "logout-button btn btn-danger float-end" %>
  </div>
</div>