config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'form_capacities/edit'
  get 'form_capacities/update'
  resources :inventory_histories
  resources :inventories do
    collection do
      get 'generate_report'
    end
  end
  resources :staff_activities
  resources :club_advisors
  resources :clubs_advisors
  resources :students do
    member do
      patch :update_score
    end
  end
  resources :staffs do
    collection do
      get 'studentsList', to: 'staffs#studentsList'
      get 'staffList', to: 'staffs#staffList' # Adding staffList route
    end
  
    member do
      get 'stuInfo/:id', to: 'staffs#stuInfo', as: 'stuInfo' 
    end
  end
  resources :club_members
  resources :attendances
  resources :extra_activities

  resources :clubs do
    resource :form_capacity, only: [:edit, :update]
    get 'edit_form_capacity', to: 'clubs#edit_form_capacity', on: :member
    resources :activities, only: [:new, :create]
    collection do
      get 'displayactivity'
      #This means, if the clubs/xx equals to one of the gets below, lead to the to: page
      get 'finance', to: 'clubs#finance'
      get 'editBudget', to: 'clubs#editBudget'
      get 'generate_report', to: 'clubs#generate_report', format: :csv
    end
  end

  resources :activities do
    collection do
      get 'editBudget'
      get 'displayactivity'
    end
  end

  

  
  get 'dashboard/generate_report', to: 'dashboard#generate_report', format: :csv, as: 'generate_report_dashboard'
  get '/clubs/show_students/:staff_id/:club_id', to: 'clubs#show_students', as: :show_students
  get 'dashboard/myTable', to: 'dashboards#my_table'
  get 'clubs/finance'
  root 'sessions#new'
  get 'dashboard', to: 'dashboard#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'activities/createActivity', to: 'activities#createActivity', as: 'createActivity'
  post '/upload', to: 'activities#upload'
  get 'activities/:id/media' => 'activities#media', as: :activity_media
  get 'attendances/:id/media' => 'attendances#media', as: :attendance_media

  get 'extra_activities/:id/evidence' => 'extra_activities#evidence', as: :extra_activity_evidence



end

app/models/activity.rb
# app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :club
  has_many :attendance
  has_many :attendances
  has_many :club_advisors
  has_many :staffs, through: :club_advisors
  has_many :staff_activities
  has_many :staff, through: :staff_activities

  after_save :deduct_budget_from_club, if: -> { saved_change_to_status? && status == 'Approved' }

  attribute :status, :string, default: 'Pending'

  private


def deduct_budget_from_club
  return unless status_was == 'Pending' && status == 'Approved' && club_id.present?

  club = Club.find_by(id: club_id)
  
  if club.present? && club.budget >= requested_budget
    club.update(budget: club.budget - requested_budget)
  end
end

def self.approved
  where(status: "approved")
end

def self.pending
  where(status: "pending")
end

#testing
  scope :upcoming_activities, -> {
    where('start_date > ?', Time.current)
      .where('end_date > ?', Time.current)
      .order('start_date ASC')
      .limit(4)
  }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :set_activity, except: [:displayactivity]
    skip_before_action :set_activity, only: [:displayactivity]
    protect_from_forgery with: :null_session, only: [:upload]


  # GET /activities or /activities.json
  def index
    @activities = Activity.all
    
  end

  #upload media
  def upload
    uploaded_file = params[:mediaFile]
    
    # Convert the uploaded file to binary
    binary_data = uploaded_file.read
    
    # Find the activity where you want to store the media
    activity = Activity.find(params[:id])
    
    # Store the binary data in the 'media' column
    # You might want to store the original filename and content type as well
    activity.media = {
      data: Base64.encode64(binary_data),
      filename: uploaded_file.original_filename,
      content_type: uploaded_file.content_type
    }
    
    # Save the activity
    if activity.save
      flash[:notice] = 'File uploaded successfully'
    else
      flash[:alert] = 'There was an error uploading the file'
    end
  
    redirect_to action: 'show', id: activity.id
    
  end
  
  

  def media
    activity = Activity.find(params[:id])
    send_data(Base64.decode64(activity.media['data']), 
              type: activity.media['content_type'], 
              disposition: 'inline')
  end
  


    # GET /activities/1 or /activities/1.json
    def show
      @activities = Activity.all
      @activity = Activity.find_by(id: params[:id])
    end

    # GET /activities/new
    def new
      @activity = Activity.new
      @clubs = Club.all
      @club = Club.find(params[:club_id]) if params[:club_id].present?
      @club_names = Club.pluck(:name, :id)
    end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    # @activity.staff_activities.build(staff_id: current_user.id)
    
    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

    # GET /activities/1/edit
    def edit
      @club_names = Club.pluck(:name, :id)
    end


  def update
    if activity_params[:update_type] == 'status'
      if activity_params[:status].in?(['approved', 'rejected'])
        if update_status(activity_params[:status])
          render json: { status: activity_params[:status].capitalize }
        else
          render json: { error: 'Invalid status or insufficient budget' }, status: :unprocessable_entity
        end
      else
        render json: { error: 'Invalid status' }, status: :unprocessable_entity
      end
    else
      respond_to do |format|
        if @activity.update(activity_params.except(:update_type, :status))
          format.html { redirect_to action: 'show', id: @activity.id, notice: 'Budget successfully updated' }
          format.json { render json: { message: 'Budget successfully updated' } }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: { error: 'Failed to update budget' }, status: :unprocessable_entity }
        end
      end
    end
  end

  def approve_budget
    if @activity.status == 'Pending'
      ActiveRecord::Base.transaction do
        @activity.update(status: 'Approved')
        club = @activity.club
        club.update(budget: club.budget - @activity.requested_budget) if club.present?
      end
      true
    else
      false
    end
  end

  def reject_budget
    # Implement the logic to reject the budget here
    # For example:
    if @activity.status == 'Pending' # Adjust this condition based on your logic
      @activity.update(status: 'Rejected')
      true
    else
      false
    end
  end


    def update_status(new_status)
      if new_status == 'approved' && approve_budget
        true
      elsif new_status == 'rejected' && reject_budget
        true
      else
        false
      end
    end
  



    # DELETE /activities/1 or /activities/1.json
    def destroy
      @activity.staff_activities.destroy_all
      @activity.attendances.destroy_all
      @activity.destroy!
        redirect_to dashboard_path, notice: "Activity was successfully destroyed."
    end

  # app/controllers/activities_controller.rb

  def displayactivity
    @clubs = Club.includes(:activities)

    if @clubs.present?
      # Render the view
    else
      Rails.logger.debug("No clubs found: #{@clubs}")
      redirect_to activities_path, alert: 'No clubs found.'
    end
  end


    def finance
      @clubs = Club.all
      @activities = Activity.all
    end

    def editBudget
      @activities = Activity.all
    end

    def allocate_budget
      if @activity.present? && @activity.status == 'Approved'
        club = @activity.club
        if club.present? && club.budget >= @activity.requested_budget
          club.update(budget: club.budget - @activity.requested_budget)
          redirect_to activity_path(@activity), notice: 'Budget successfully allocated.'
        else
          redirect_to activity_path(@activity), alert: 'Insufficient budget for allocation.'
        end
      else
        redirect_to activities_path, alert: 'Activity not found or budget not approved.'
      end
    end
    
    private
    
    def set_activity
      @activity = params[:id].present? && params[:id] != 'displayactivity' ? Activity.find(params[:id]) : nil
    end
    
    def activity_params
      params.require(:activity).permit(:activity_title, :description, :start_date, :end_date, :requested_budget, :club_id, :update_type, :status)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def is_mobile?
        browser.device.mobile?
    end
      
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>" class="card bg-light mb-3">
  <div class="card-body">
    <h5 class="card-title"><strong>Activity Title:</strong> <%= activity.activity_title %></h5>
    <p class="card-text">
      <strong>Description:</strong>
      <%= activity.description %>
    </p>
    <p class="card-text">
      <strong>Start Date:</strong>
      <%= activity.start_date %>
    </p>
    <p class="card-text">
      <strong>End Date:</strong>
      <%= activity.end_date %>
    </p>
    <p class="card-text">
      <strong>Allocated Budget (RM):</strong>
      <%= number_with_precision(activity.requested_budget, precision: 2) %>
    </p>
    <p class="card-text">
      <strong>Club:</strong>
      <%= activity.club_id %>
    </p>
  </div>
</div>

app/views/activities/_editform.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
  <%= form.label :activity_title, class: "form-label" %>
  <%= form.text_field :activity_title, class: "form-control", id: "floatingInput", placeholder: "Activity Title" %>
</div>

<div class="mb-3">
  <%= form.label :description, class: "form-label" %>
  <%= form.text_area :description, class: "form-control", id: "floatingTextarea", placeholder: "Description" %>
</div>

<div class="mb-3">
  <%= form.label :start_date, class: "form-label" %>
  <%= form.date_field :start_date, class: "form-control", id: "floatingStartDate", placeholder: "Start Date" %>
</div>

<div class="mb-3">
  <%= form.label :end_date, class: "form-label" %>
  <%= form.date_field :end_date, class: "form-control", id: "floatingEndDate", placeholder: "End Date" %>
</div>
<script>
  document.getElementById('floatingStartDate').addEventListener('change', function() {
    document.getElementById('floatingEndDate').min = this.value;
  });
</script>
  <div>
    <%= form.submit "Save Activity", class:"btn btn-success mb-3 col-12" %>
  </div>
<% end %>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if @activity.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
      <ul>
        <% @activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="mb-3">
  <%= form.text_field :activity_title, required: true, class: "form-control", id: "floatingTitle", placeholder: "Activity Title" %>
</div>
  <div class="mb-3">
    <%= form.text_area :description, class: "form-control", id: "floatingTextarea", placeholder: "Description" %>
  </div>
<div class="mb-3">
  <%= form.date_field :start_date, required: true, class: "form-control", id: "floatingStartDate", placeholder: "Start Date" %>
</div>
<div class="mb-3">
  <%= form.date_field :end_date, required: true, class: "form-control", id: "floatingEndDate", placeholder: "End Date" %>
</div>

<script>
  document.getElementById('floatingStartDate').addEventListener('change', function() {
    document.getElementById('floatingEndDate').min = this.value;
  });
</script>
<div class="mb-3">
  <%= form.text_field :requested_budget, required: true, pattern: "\\d*", title: "Only numbers are allowed.", class: "form-control", id: "floatingBudget", placeholder: "Requested Budget (RM)"  %>
</div>
  <div class="mb-3">
    <%= form.select :club_id, options_for_select(current_user.club_advisors.map { |club_advisor| [club_advisor.club.name, club_advisor.club.id] }), {}, { class: "form-control", id: "floatingClubID", placeholder: "Select Club" } %>
 </div>
  <div>
    <%= form.submit "Submit Activity",  class: "btn btn-success col-12" %>
  </div>
<% end %>

app/views/activities/_index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Activities</h1>

<table class="table table-striped table-hover table-bordered border-dark">
  <thead>
    <tr>
      <th>Activity Title</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Requested Budget (RM)</th>
      <th>Club Name</th>
      <th colspan="2" style="text-align: center;">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_title %></td>
        <td><%= activity.description %></td>
        <td><%= activity.start_date %></td>
        <td><%= activity.end_date %></td>
        <td><%= number_with_precision(activity.requested_budget, precision: 2) %></td>
        <td><%= activity.club.name %></td>
        <td><%= link_to 'Show Activity', activity, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Attendance', new_attendance_path(activity_id: activity.id), class: 'btn btn-info btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Activity', new_activity_path, class: 'btn btn-success' %>

app/views/activities/displayactivity.html.erb
<!-- app/views/activities/displayactivity.html.erb -->

<h1>Display Activity</h1>

<% if @clubs.present? %>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Club Name</th>
          <th>Activities</th>
        </tr>
      </thead>
      <tbody>
        <% @clubs.each do |club| %>
          <tr>
            <td><%= club.name %></td>
            <td>
              <%= club.activities.pluck(:activity_title).join(', ') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No clubs and activities found.</p>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit activity</h1>
<%= render "editform", activity: @activity %>

app/views/activities/editBudget.html.erb
<% content_for :javascript do %>


<script>
  async function updateBudget(activityId, status) {
    const token = document.getElementsByName('csrf-token')[0].content;

    try {
      const response = await fetch(`/activities/${activityId}.json?activity[status]=${status}&activity[update_type]=status`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'X-CSRF-Token': token
        }
      });

      if (response.ok) {
        const data = await response.json();
        handleUpdateResponse(data, activityId);
      } else {
        const errorData = await response.json(); // Attempt to get more error details
        console.error('Error updating budget:', errorData);
        alert('Error updating budget. Can not approve or reject anymore.');
      }
    } catch (error) {
      console.error('Exception:', error);
      alert('Error updating budget. Can not approve or reject anymore.');
    }
  }

  function handleUpdateResponse(data, activityId) {
    console.log('Update response data:', data);
    console.log('Activity ID:', activityId);

    const statusColumn = document.getElementById(`status-${activityId}`);
    if (statusColumn) {
      statusColumn.innerHTML = data.status.charAt(0).toUpperCase() + data.status.slice(1).toLowerCase();

      if (data.status === 'Rejected') {
        alert('Budget Rejected');
      } else if (data.status === 'Approved') {
        alert('Budget Approved');
      } else {
        alert('Unexpected response. Please check the console for details.');
      }
    } else {
      console.error('Status column not found for activity ID:', activityId);
      alert('Error updating budget. Can not approve or reject anymore.');
    }
  }
</script>
<% end %>

<% @activities.group_by { |activity| activity.club.category }.each do |category, category_activities| %>
  <h1><%= category %> Category Activities</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Activity Id</th>
        <th>Activity Title</th>
        <th>Requested Budget(RM)</th>
        <th>Available Budget(RM)</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% category_activities.each do |activity| %>
        <tr>
          <td data-label = "Activity Id"><%= activity.id %></td>
          <td data-label = "Activity Title"><%= activity.activity_title %></td>
          <td data-label = "Requested Budget (RM)"><%= number_with_precision(activity.requested_budget, precision: 2) %></td>
          <td data-label = "Available Budget (RM)", id="available-budget-<%= activity.id %>"><%= number_with_precision(activity.club.budget, precision: 2) %></td>
          <td data-label = "Status", id="status-<%= activity.id %>"><%= activity.status %></td>
          <td>
            <% unless activity.status.in?(['approved', 'rejected']) %>
              <!-- Only show the buttons if the budget is neither approved nor rejected -->
              <div class="btn-group d-flex justify-content-between">
  <button class="btn btn-success flex-fill" onclick="updateBudget(<%= activity.id %>, 'approved')">Approve</button>
  <button class="btn btn-danger flex-fill" onclick="updateBudget(<%= activity.id %>, 'rejected')">Reject</button>
</div>



            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back to Finance', finance_clubs_path, class: 'btn btn-primary mb-3 col-12' %>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Activities</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Activity Title</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Requested Budget (RM)</th>
      <th>Club ID</th>
      <th colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_title %></td>
        <td><%= activity.description %></td>
        <td><%= activity.start_date %></td>
        <td><%= activity.end_date %></td>
        <td><%= number_with_precision(activity.requested_budget, precision: 2) %></td>
        <td><%= activity.club_id %></td>
        <td><%= link_to 'Show', activity, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Attendance', new_attendance_path(activity_id: activity.id), class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Activity', new_activity_path, class: 'btn btn-success' %>

app/views/activities/new.html.erb
<div >
  <h1 class="display-4">New Activity</h1>
  <%= render "form", club: @club, activity: @activity %>
  <br>
  <div>
    <%= link_to "Back to dashboard", dashboard_path, class:"btn btn-primary mb-3 col-12" %>
  </div>
</div>

app/views/activities/show.html.erb
<!-- app/views/activities/show.html.erb -->
<% if flash[:notice] %>
  <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert alert-danger"><%= flash[:alert] %></p>
<% end %>
<div class="container mt-4">
  <h1>Activity Details</h1>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">Activity Title</th>
        <td><%= @activity.activity_title %></td>
      </tr>
      <tr>
        <th scope="row">Description</th>
        <td><%= @activity.description %></td>
      </tr>
      <tr>
        <th scope="row">Start Date</th>
        <td><%= @activity.start_date %></td>
      </tr>
      <tr>
        <th scope="row">End Date</th>
        <td><%= @activity.end_date %></td>
      </tr>
      <tr>
        <th scope="row">Requested Budget (RM)</th>
        <td><%= number_with_precision(@activity.requested_budget, precision: 2) %></td>
      </tr>
      <tr>
        <th scope="row">Club</th>
        <td><%= @activity.club.name if @activity.club %></td>
      </tr>
      <tr>
        <%= form_tag({ action: 'upload', id: @activity.id }, multipart: true, remote: true, html: { id: 'upload-form' }) do %>
      <%= hidden_field_tag :id, @activity.id %>
      <%= csrf_meta_tags %>
        <th scope="row">Upload Media</th>
        <td><input type="file" id="mediaFile" name="mediaFile" accept="image/*, video/*">
            <input type="submit" value="Upload" class="btn btn-info"></td>
            <% end %>
      </tr>
      
      <% if @activity.media %>
      <tr>
        <th scope="row">Media Uploaded</th>
        <td><%= @activity.media['filename'] %><%= link_to ' Download Media', activity_media_path(@activity.id), download: @activity.media['filename'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to "Edit this activity", edit_activity_path(@activity), class: "btn btn-warning mb-3 col-12" %>
    <%= button_to "Delete this activity", @activity, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mb-3 col-12" %>
    <%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-primary mb-3 col-12" %>
  </div>
</div>